/**
 * Prepares a fresh clone to talk to Postgres, so `npm run setup` is the only
 * command a reviewer has to run.
 *
 * Two things stand between a clone and a working app, and both are easy to get
 * wrong by hand:
 *
 *   1. `.env` has to exist. Prisma resolves `env("DATABASE_URL")` at startup and
 *      `.env` is gitignored, so there is nothing to inherit from the repo.
 *   2. That URL needs an explicit username. `psql` falls back to the OS user
 *      when the connection string omits it; Prisma's query engine does not — it
 *      sends an empty user and Postgres answers P1010. Since the right username
 *      differs per machine, no committed default can work for everyone, which is
 *      why this is generated rather than checked in.
 *
 * Everything here is idempotent and non-destructive: an existing `.env` is left
 * exactly as it is, and an existing database is left exactly as it is.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { userInfo } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");

/** Docker and password-protected installs need a different string than we generate. */
const DOCKER_HINT = `
  If you are running Postgres in Docker, or your install needs a password,
  set the connection string by hand instead:

    DATABASE_URL="postgresql://postgres:postgres@localhost:5432/the_block?schema=public"

  in ${envPath}, then re-run npm run setup.`;

/** True if a CLI is callable, used to tell "no Postgres tools" from "tools failed". */
function isAvailable(command) {
  try {
    execFileSync(command, ["--version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

/** The URL already in play, if any: a real env var wins over the .env file. */
function existingUrl() {
  if (process.env.DATABASE_URL) {
    return { url: process.env.DATABASE_URL, source: "the DATABASE_URL environment variable" };
  }
  if (existsSync(envPath)) {
    const match = readFileSync(envPath, "utf8").match(/^\s*DATABASE_URL\s*=\s*"?([^"\n]+)"?/m);
    if (match) return { url: match[1], source: ".env" };
  }
  return null;
}

function ensureEnvFile() {
  const existing = existingUrl();
  if (existing) {
    console.log(`• DATABASE_URL found in ${existing.source} — leaving it alone`);
    return existing.url;
  }

  // process.env.USER is absent under some launchers; userInfo() always resolves.
  const user = process.env.USER || userInfo().username;
  const url = `postgresql://${user}@localhost:5432/the_block?schema=public`;

  writeFileSync(
    envPath,
    `# Generated by scripts/init-env.mjs. Edit freely — setup will not overwrite it.\n` +
      `DATABASE_URL="${url}"\n`,
  );
  console.log(`• Wrote .env  →  ${url}`);
  return url;
}

function ensureDatabase(url) {
  let name;
  try {
    name = new URL(url).pathname.slice(1);
  } catch {
    console.error(`✗ DATABASE_URL is not a valid URL: ${url}`);
    process.exit(1);
  }

  if (!name) {
    console.error(`✗ DATABASE_URL has no database name: ${url}`);
    process.exit(1);
  }

  if (!isAvailable("createdb")) {
    // Nothing to do but hand it back to the reader — Postgres may well be
    // running in Docker, where createdb on the host is not expected.
    console.log(`• createdb not on PATH — skipping database creation`);
    console.log(`  Create "${name}" yourself if it does not exist, then re-run.`);
    return;
  }

  try {
    execFileSync("createdb", [name], { stdio: ["ignore", "ignore", "pipe"] });
    console.log(`• Created database "${name}"`);
  } catch (error) {
    const stderr = String(error.stderr ?? "");
    if (stderr.includes("already exists")) {
      console.log(`• Database "${name}" already exists — reusing it`);
      return;
    }
    console.error(`✗ Could not create database "${name}":`);
    console.error(stderr.trim() || error.message);
    if (stderr.includes("could not connect")) {
      console.error(`\n  Is Postgres running? On macOS/Homebrew:  brew services start postgresql@16`);
    }
    console.error(DOCKER_HINT);
    process.exit(1);
  }
}

ensureDatabase(ensureEnvFile());
